name: example-run

on:
  pull_request:
    branches:
        - main
        - "v*"
  push:
    branches:
      - main

permissions:
  contents: write
  
env:
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly

jobs:

  run-bevy_maze-example-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev libxkbcommon-x11-0  libwayland-dev; 
      - name: install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/turtle -y
          sudo apt-get update
          sudo apt install -y xvfb libgl1 libglx-mesa0 libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Build bevy
        # this uses the same command as when running the example to ensure build is reused
        run: CARGO_PROFILE_RELEASE_DEBUG=true TRACE_CHROME=trace-bevy_maze.json cargo +nightly build --example bevy --release --features "bevy/bevy_ci_testing,bevy/trace_chrome,bevy/trace,backtrace"
        env:
          RUSTFLAGS: "-C debuginfo=0"
      - name: Run examples
        env:
          RUSTFLAGS: "-C debuginfo=0"
        run: |
          example_name=`basename bevy_maze`
          echo -n $example_name > last_example_run
          echo "running bevy_maze - "`date`
          time CARGO_PROFILE_RELEASE_DEBUG=true TRACE_CHROME=trace-bevy_maze.json xvfb-run cargo +nightly run --release --example bevy --features "backtrace,bevy/bevy_ci_testing,bevy/trace_chrome,bevy/trace"
          sleep 10
          if [ `find ./ -maxdepth 1 -name 'screenshot-*.png' -print -quit` ]; then
            mkdir screenshots-bevy_maze
            mv screenshot-*.png screenshots-bevy_maze/
          fi
          mkdir traces && mv trace*.json traces/
          mkdir screenshots && mv screenshots-* screenshots/
      - name: save traces
        uses: actions/upload-artifact@v4
        with:
          name: example-traces-linux-bevy_maze-${{ steps.date.outputs.date }}
          path: traces
      - name: save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-linux-bevy_maze-${{ steps.date.outputs.date }}
          path: screenshots
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          name: example-run-linux-bevy_maze-${{ steps.date.outputs.date }}
          path: example-run/
  
  