name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v6
    - name: Check spelling
      uses: crate-ci/typos@master
      
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Format
      run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install stable@stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Install Dependencies
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev
    - name: Run Clippy
      run: cargo clippy --locked --all-features --all-targets

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: check
        run: cargo check --locked --all-features

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev
      - name: Test
        run: cargo test --locked --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    # container:
    #   image: xd009642/tarpaulin:develop-nightly
    #   options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install nightly@nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin --locked
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --all-features --workspace --timeout 300 --out Lcov --output-dir ./coverage
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2

  run-example-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev libxkbcommon-x11-0  libwayland-dev; 
      - name: install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo apt install ppa-purge
          sudo ppa-purge ppa:kisak/turtle -y
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Build bevy
        # this uses the same command as when running the example to ensure build is reused
        run: CARGO_PROFILE_RELEASE_DEBUG=true TRACE_CHROME=trace-example.json CI_TESTING_CONFIG=.github/data/example.ron cargo +nightly build --example bevy_pathfinding --release --features "bevy/bevy_ci_testing,bevy/trace_chrome,bevy/trace,backtrace"
        env:
          RUSTFLAGS: "-C debuginfo=0"
      - name: Run examples
        env:
          RUSTFLAGS: "-C debuginfo=0"
        run: |
          example_name=`basename example.ron`
          echo -n $example_name > last_example_run
          echo "running example - "`date`
          time CARGO_PROFILE_RELEASE_DEBUG=true TRACE_CHROME=trace-example.json CI_TESTING_CONFIG=.github/data/example.ron xvfb-run cargo +nightly run --release --example bevy_pathfinding --features "bevy/bevy_ci_testing,bevy/trace_chrome,bevy/trace,backtrace"
          sleep 10
          if [ `find ./ -maxdepth 1 -name 'screenshot-*.png' -print -quit` ]; then
            mkdir screenshots-example
            mv screenshot-*.png screenshots-example/
          fi
          mkdir traces && mv trace*.json traces/
          mkdir screenshots && mv screenshots-* screenshots/
      - name: save traces
        uses: actions/upload-artifact@v4
        with:
          name: example-traces-linux-example-${{ steps.date.outputs.date }}
          path: traces
      - name: save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-linux-example-${{ steps.date.outputs.date }}
          path: screenshots
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          name: example-run-linux-example-${{ steps.date.outputs.date }}
          path: example-run/
